[Service]
# Vyčistíme starý príkaz
ExecStart=
# Spustíme logid s vynúteným prostredím z bashu
ExecStart=/usr/bin/bash -c "HOME=/root XDG_RUNTIME_DIR=/run/user/0 /usr/local/bin/logid"

# POČKÁME 10 sekúnd pred samotným štartom, nech sa udev/bluetooth stihnú prebrať
ExecStartPre=/usr/bin/sleep 10

# Ak logid stratí myš alebo ju nenájde, systemd ho zabije a o 5 sekúnd skúsi znova
Restart=always
RestartSec=5s
