# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

#############################################
################ MY SETTINGS ################
#############################################

# Remove default shotcuts:
unbind = SUPER, down
unbind = SUPER, up
unbind = SUPER, DOWN
unbind = SUPER, UP

unbind = SUPER, k
unbind = SUPER, K
unbind = SUPER, j
unbind = SUPER, J

unbind = SUPER, h
unbind = SUPER, H
unbind = SUPER, l
unbind = SUPER, L

unbind = SUPER, LEFT
unbind = SUPER, left
unbind = SUPER, RIGHT
unbind = SUPER, right

# Move focus to windows on left / right
bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r

# Move to other workspaces up / down
bind = SUPER, j, workspace, r+1
bind = SUPER, k, workspace, r-1
bind = SUPER, down, workspace, r+1
bind = SUPER, up, workspace, r-1

# Move window to other workspaces, take with cursor
bind = SUPER SHIFT, j, movetoworkspace, r+1
bind = SUPER SHIFT, k, movetoworkspace, r-1
bind = SUPER CONTROL, down, movetoworkspace, r+1
bind = SUPER CONTROL, up, movetoworkspace, r-1

# Move window to other monitors / locations
bind = SUPER SHIFT, h, movewindow, l
bind = SUPER SHIFT, l, movewindow, r
bind = SUPER CONTROL, left, movewindow, l
bind = SUPER CONTROL, right, movewindow, r

# Open terminal
bind = SUPER, return, exec, $terminal
bind = SUPER, T, exec, $terminal

# bind = SUPER, F, exec, uwsm app -- nautilus --new-window
bind = SUPER, E, exec, /opt/google/chrome/google-chrome &
bind = SUPER, M, exec, uwsm app -- spotify
bind = SUPER, N, exec, omarchy-launch-tui nvim
bind = SUPER, Y, exec, omarchy-launch-tui btop
bind = SUPER, D, exec, omarchy-launch-tui lazydocker

# Lock the workstation
bind = CTRL ALT, ncaron, exec, loginctl lock-session

# Toggle layout orientation
bind = CTRL ALT, o, layoutmsg, togglesplit


#############################################
############## END MY SETTINGS ##############
#############################################
