general {
    lock_cmd = omarchy-system-lock
    before_sleep_cmd = OMARCHY_LOCK_ONLY=true omarchy-system-lock
    after_sleep_cmd = sleep 1 && omarchy-system-wake
    inhibit_sleep = 3
}

# Lock after 15 minutes
listener {
    timeout = 900
    on-timeout = omarchy-system-lock
}

# Optional keyboard backlight handling
# listener {
#     timeout = 10
#     on-timeout = brightnessctl -sd '*::kbd_backlight' set 0
#     on-resume = brightnessctl -rd '*::kbd_backlight'
# }

# Optional screen off after 5.5 minutes
# listener {
#     timeout = 330
#     on-timeout = hyprctl dispatch dpms off
#     on-resume = hyprctl dispatch dpms on && brightnessctl -r
# }

